FROM nginx:alpine

# 时区
RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

# 复制前端构建产物
COPY web/dist/ /usr/share/nginx/html/

# 复制 Nginx 配置
COPY deploy/docker-nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
