-- OCR识别配置：在 ai_config 表新增 OCR 相关字段
ALTER TABLE ai_config ADD COLUMN IF NOT EXISTS ocr_api_url VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE ai_config ADD COLUMN IF NOT EXISTS ocr_api_key VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE ai_config ADD COLUMN IF NOT EXISTS ocr_model VARCHAR(100) NOT NULL DEFAULT 'Qwen/Qwen2.5-VL-72B-Instruct';
ALTER TABLE ai_config ADD COLUMN IF NOT EXISTS ocr_enabled BOOLEAN NOT NULL DEFAULT true;
